### ISSUE TITLE
How do you split the dataset?

### ISSUE THREAD

**Issue by taylor-xy0827** [hangyu94/Ada-CM#5]
Dear author, thank you for your great work! But I am confused about your dataset setup because the RAF-DB dataset I downloded from the official website seems to not organized like yours. Can you explicitly explain how you split the dataset or how you preprocess it?

![2022-06-22 111527](https://user-images.githubusercontent.com/89014020/174935879-7d498a11-91d2-40fd-80e8-7a4b9a47aa48.png)

**Comment by hangyu94** [comment]
In our work, we do not split or preprocess the official RAF-DB. The data and labels used in our experiments come from the EmoLabel Folder and the Image Folder, respectively. Therefore, you just need to change the root to your path to run this code.

**Comment by hangyu94** [comment]
About the error, I think maybe it is because there are three values for each sample read from our label files, i.e., filename (xxxx.jpg), labels (from 0 to 6) and the coarse-grained labels (which are unrelated to this work and are not used in this work. Of course, if you are interested in it, welcome to refer our another two papers [1][2]). Finally, to address this error caused in your situation, you can modify the 41-th line and the 90-th line in /dataset/raf.py into '_, label_name = info.split(' ')' and 'image_path, label_name = info.split(' ')', respectively. In other words, to successfully run our code in your workstation, you can just read two values from your files. In addition, we have modified the labels 1-7 provided in original RAF-DB into 0-6. Because PyTorch cannot support the labels from 1 to 7.
[1] Adaptively Learning Facial Expression Representation via C-F Labels and Distillation, IEEE TIP 2021.
[2] CRS-CONT: A Well-Trained General Encoder for Facial Expression Analysis, IEEE TIP 2022.

**Comment by Sizero2one** [comment]
I have the following problem when running the code: TypeError: img should be PIL Image. Got <class 'NoneType'>.Could you tell me how to fix it? Thanks!
